--Insercion de datos en ALUMNO_12
INSERT INTO ALUMNO_12(NO_CTA,NOMBRE_A,ESPECIALIDAD,DIR)
VALUES(984431,'PEDRO LOPEZ JUAREZ','INFORMATICA','ELEUTERIO MENDEZ NO. 37')
INSERT INTO ALUMNO_12(NO_CTA,NOMBRE_A,ESPECIALIDAD,DIR)
VALUES(990123,'ERNESTO MUÑOS PEREZ','PSICOLOGIA','TOMAS VAZQUEZ 29')
INSERT INTO ALUMNO_12(NO_CTA,NOMBRE_A,ESPECIALIDAD,DIR)
VALUES(970205,'AMARANTA BENITEZ CASTRO','DERECHO','ZAMORAS 45')
INSERT INTO ALUMNO_12(NO_CTA,NOMBRE_A,ESPECIALIDAD,DIR)
VALUES(990136,'JESUS ARTEAGA VENEGAS','ADMINISTRACION','CANARIAS 93-3')

--Insercion de datos en CURSA_12
INSERT INTO CURSA_12(NO_CTA,CLAVE_MAT,CALIF)
VALUES(984431,'IN001',10)
INSERT INTO CURSA_12(NO_CTA,CLAVE_MAT,CALIF)
VALUES(990123,'PS001',7)
INSERT INTO CURSA_12(NO_CTA,CLAVE_MAT,CALIF)
VALUES(970205,'DE001',10)
INSERT INTO CURSA_12(NO_CTA,CLAVE_MAT,CALIF)
VALUES(990136,'AD001',8)
INSERT INTO CURSA_12(NO_CTA,CLAVE_MAT,CALIF)
VALUES(984431,'IN002',9)
INSERT INTO CURSA_12(NO_CTA,CLAVE_MAT,CALIF)
VALUES(990123,'PS002',9)
INSERT INTO CURSA_12(NO_CTA,CLAVE_MAT,CALIF)
VALUES(970205,'DE002',7)
INSERT INTO CURSA_12(NO_CTA,CLAVE_MAT,CALIF)
VALUES(990136,'AD002',6)


--CONSULTAS
--A)
SELECT NOMBRE_A,NO_CTA FROM ALUMNO_12
GROUP BY NOMBRE_A
GO

--B)
SELECT NOMBRE_MAT,CREDITOS
FROM MATERIA_12
GROUP BY NOMBRE_MAT
GO
--C)

SELECT NOMBRE_A, NOMBRE_MAT FROM ALUMNO_12, CURSA_12, MATERIA_12
WHERE ALUMNO_12.NO_CTA = CURSA_12.NO_CTA AND CURSA_12.CLAVE_MAT = MATERIA_12.CLAVE_MAT
ORDER BY NOMBRE_MAT, NOMBRE_A

--D)
SELECT NOMBRE_A, AVG(CALIF),  ESPECIALIDAD FROM ALUMNO_12
JOIN CURSA_12 ON ALUMNO_12.NO_CTA = CURSA_12.NO_CTA
GROUP BY ESPECIALIDAD
HAVING AVG(CALIF) > 8
ORDER BY NOMBRE_A, AVG(CALIF)

--E)
SELECT NOMBRE_A FROM ALUMNO_12 WHERE ESPECIALIDAD LIKE 'P%'
ORDER BY NOMBRE_A